services:
  - type: web
    name: amazon-bulk-campaign-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: WORDPRESS_URL
        value: "https://ecommercean.com"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
